import { Inter } from "next/font/google";
import "./userdashboard/ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>{children}</body>
    </html>
  );
}

// Layout and Template files used for same thing. But difference between both of them is that when we use layout.js file then only that partucular component will will be render its related component will not re-render. But in case of template its related components ad=nd state gets re-rendered or gets reset.
